## Standards checklist:
r-darwish/topgrade pull request #518
Opened 2020-09-04 19:22 UTC by FallenWarrior2k

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

2020-09-04 19:23 UTC, FallenWarrior2k commented
Sorry, I was using the CLI and misclicked (wanted to cancel instead of save).

2020-09-04 20:01 UTC, r-darwish requested changes

2020-09-04 21:16 UTC, FallenWarrior2k commented on src/steps/vim.rs
> +    let base_dir = base_dirs.config_dir();
I have two ideas on how to circumvent this:

- Special-case macOS with `cfg(all(unix, not(target_os = "macos")))`
- Mimic Neovim's (documented) behavior by partially bypassing the `directories` crate and using the following (or similar):
```
#[cfg(unix)]
let base_dir =
    std::env::var_os("XDG_CONFIG_HOME").map_or_else(|| base_dirs.home_dir().join(".config"), PathBuf::from);
```

First seems brittle, so I'd be partial to the latter.

2020-09-06 13:09 UTC, r-darwish commented on src/steps/vim.rs
> +    let base_dir = base_dirs.config_dir();
I'm in favor of the latter as well.

2020-09-06 16:43 UTC, r-darwish approved these changes

2020-09-06 16:44 UTC, merged