Drop the Go step
r-darwish/topgrade pull request #660
Opened 2021-02-24 07:17 UTC by Akeshihiro

With the release of Go 1.16 the behavior of `go get` has been changed.
In previous Go versions `go get` was used not only to add module
dependencies but also to install Go tools.
As of Go 1.16 `go get` can only add and upgrade module dependencies.
To install Go tools now the `go install` command has to be used.

Further on Go 1.16 enabled the GOMODULE mode by default and will drop
the GOPATH mode completly in Go 1.17.
So the package definition `all` like in `go get -u all` does not work
anymore if the PWD is outside of a Go module project.
Because of this `go list all` also does not work for the same reason.
That being said it seems that currently there is no way to get a list of
all installed Go tools or packages at the GOPATH level.

So the only possible solution to determine the installed Go tools and
also to update them would be by inspecting the `go env GOBIN` directory
as well as the `go env GOMODCACHE` sub-directories and to filter the
results according to their possible name-to-package boundaries.
As this approach seems to be very ugly and also not to be very safe or
stable and Go currently does not support any kind of automated upgrades
of installed Go tools it is best to drop the Go step for now until Go
implements some kind of Go tool upgrade feature.

Fixes #659

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

2021-02-24 07:27 UTC, r-darwish requested changes
Please also remove `Step::Go` from `config.rs`

2021-02-24 10:17 UTC, merged

2021-02-24 10:17 UTC, r-darwish commented
Good riddance 😄 
Thank you

2021-02-24 17:15 UTC, Akeshihiro commented
Thank you for this great tool. I'm using topgrade for some month now across multiple devices and OSes and it works like a charm. Sometimes making some upgrades really is a nightmare! So yeah, very happy with topgrade :-)

2021-03-01 09:06 UTC, thomwiggers commented
Go has not been removed from the wiki pages describing supported steps yet.

2021-03-01 09:37 UTC, r-darwish commented
@thomwiggers fixed